print("====================================")
print("    Welcome to Holiday Planner!     ")
print("====================================")
print()
print("Step 1: Pick your holiday type")
print("  1 - Beach Holiday")
print("  2 - Mountain Holiday")
print()
choice = int(input("Enter 1 or 2: "))
print()
if choice == 1:
    # Nested if-else — runs only when choice is 1
    print("Step 2: Pick your beach activity")
    print("  1 - Swimming")
    print("  2 - Beach Volleyball")
    print()
    beach_activity = int(input("Enter 1 or 2: "))
    print()
    if beach_activity == 1:
        print("You picked  : Swimming")
        print("Best for    : Cooling off and having fun")
        print("Activity    : Enjoy a swim at the beach")
    else:
        print("You picked  : Beach Volleyball")
        print("Best for    : Playing with friends")
        print("Activity    : Have fun playing volleyball")
elif choice == 2:
    print("Step 2: Pick your mountain activity")
    print("  1 - Hiking")
    print("  2 - Camping")
    print()
    mountain_activity = int(input("Enter 1 or 2: "))
    print()
    if mountain_activity == 1:
        print("You picked  : Hiking")
        print("Best for    : Exploring nature")
        print("Activity    : Enjoy a scenic mountain hike")
    else:
        print("You picked  : Camping")
        print("Best for    : Spending time outdoors")
        print("Activity    : Enjoy a fun camping trip")
else:
    print("That was not a valid choice.")
    print("Please enter 1 for Beach Holiday or 2 for Mountain Holiday.")
print()
print("====================================")
print("   Your holiday plan is ready!      ")
print("   Have a wonderful holiday!        ")
print("====================================")