a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))
print("Before swapping:")
print("a =", a)
print("b =", b)
print("c =", c)
print("After swapping:")
print("a =", b)
print("b =", c)
print("c =", a)